version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: yarn run start:dev
    environment:
      SPANNER_PROJECT_ID: "test-project"
      SPANNER_INSTANCE_ID: "test-instance"
      SPANNER_DATABASE_ID: "test-database"
      SPANNER_EMULATOR_URL: "http://spanner:9020/"
      SPANNER_EMULATOR_HOST: "spanner:9010"

  # Spanner
  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator:1.4.1
    ports:
      - "9010:9010"
      - "9020:9020"

  # Init (Create Instance)
  gcloud-spanner-init:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:332.0.0-slim
    #volumes:
    #  - db_data:/var/lib/xxx # どこのパスにデータが保存される?
    command: >
     bash -c 'gcloud config configurations create emulator &&
             gcloud config set auth/disable_credentials true &&
             gcloud config set project $${PROJECT_ID} &&
             gcloud config set api_endpoint_overrides/spanner $${SPANNER_EMULATOR_URL} &&
             gcloud config set auth/disable_credentials true &&
             gcloud spanner instances create $${INSTANCE_NAME} --config=emulator-config --description=Emulator --nodes=1'
    environment:
      PROJECT_ID: "test-project"
      SPANNER_EMULATOR_URL: "http://spanner:9020/"
      INSTANCE_NAME: "test-instance"
      DATABASE_NAME: "test-database"

  # DB Migration (Create Table)
  wrench-crearte:
    image: mercari/wrench:1.0.3
    environment:
      SPANNER_PROJECT_ID: "test-project"
      SPANNER_INSTANCE_ID: "test-instance"
      SPANNER_DATABASE_ID: "test-database"
      SPANNER_EMULATOR_HOST: "spanner:9010"
      SPANNER_EMULATOR_URL: "http://spanner:9020/"
    volumes:
      - ./migrations/ddl:/ddl
    command: "create --directory /ddl"
    restart: on-failure

  # DB Migration (Insert data)
  wrench-apply:
    image: mercari/wrench:1.0.3
    environment:
      SPANNER_PROJECT_ID: "test-project"
      SPANNER_INSTANCE_ID: "test-instance"
      SPANNER_DATABASE_ID: "test-database"
      SPANNER_EMULATOR_HOST: "spanner:9010"
      SPANNER_EMULATOR_URL: "http://spanner:9020/"
    volumes:
      - ./migrations/dml:/dml
    command: "apply --dml /dml/insert_data.sql"
    restart: on-failure

  # Spanner CLI
  spanner-cli:
    image: sjdaws/spanner-cli:v1.0.0
    #build:
    #  context: ./docker/spanner-cli/
    #  dockerfile: ./Dockerfile
    environment:
      SPANNER_EMULATOR_HOST: "spanner:9010"
      #SPANNER_DATABASE: database_name
      #SPANNER_INSTANCE_ID: instance_id
      #SPANNER_PROJECT_ID: project_id
    command: ['sh', '-c', 'echo this container keep running && tail -f /dev/null']

